# NoBedExplosions
# made with <3 by TehBrian
#
# Control bed and respawn anchor functionality across all of your worlds,
# such as allowing sleep in the nether or the end!
#
# Modrinth: https://modrinth.com/plugin/nobedexplosions
# Discord:  https://tehbrian.dev/discord
# GitHub:   https://github.com/TehBrian/NoBedExplosions
#
# World configuration:    worlds.yml
# Language configuration: lang.yml
