name: NoBedExplosions
description: ${description}
authors: [ TehBrian ]
website: https://github.com/TehBrian/NoBedExplosions

version: ${version}
main: dev.tehbrian.nobedexplosions.NoBedExplosions
api-version: 1.20

permissions:
  nobedexplosions.reload:
    description: Permission to run /nbe reload.
    default: op
  nobedexplosions.info:
    description: Permission to run /nbe info.
    default: op
