name: NoBedExplosions
description: Control bed and respawn anchor functionality across all of your worlds, such as allowing sleep in the nether or the end!
authors: [ TehBrian ]
website: https://spigotmc.org/resources/65808

version: ${version}
main: xyz.tehbrian.nobedexplosions.NoBedExplosions
api-version: 1.18

permissions:
  nobedexplosions.reload:
    description: Permission to use /nbe reload.
    default: op
  nobedexplosions.info:
    description: Permission to use /nbe info.
    default: op
